# Pipeline for the first npm publish for abstractions.

name: Build and publish Kiota abstractions package
    
on:
  workflow_dispatch
  push:
    branches: [ main ]
    paths: ['packages/abstractions/**', '.github/workflows/**']
  pull_request:
    paths: ['packages/abstractions/**', '.github/workflows/**']

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            node-version: [14.x, 16.x, 17.x]
        steps:
        - uses: actions/checkout@v3
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
        - run: npm ci
        - run: npm run build
          working-directory: packages/abstractions
            
    publish-npm:
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        needs: build
        environment:
          name: production_feed
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-node@v3
            with:
              node-version: 16
              registry-url: https://registry.npmjs.org/
          - run: npm ci
          - run: npm run build
          - run: npm publish --access public
            working-directory: packages/abstractions
            env:
              NODE_AUTH_TOKEN: ${{secrets.npm_token}}
